// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://strquozhswmqqlwbodmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0cnF1b3poc3dtcXFsd2JvZG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5MDU2NDksImV4cCI6MjA4NzQ4MTY0OX0._Lm7gjM_OPaLAQVqEp7h3BFP1FP0nCUHvuZCQUJa2QQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});